global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "fraud_inference"
    scrape_interval: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - "inference:8000"
        labels:
          service: "fraud_detection"
          environment: "docker"
  - job_name: "prometheus"
    scrape_interval: 30s
    static_configs:
      - targets:
          - "localhost:9090"
        labels:
          service: "prometheus"
          